export const GET_PORTFOLIO = 'GET_PORTFOLIO';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROJECT = 'GET_PROJECT';
export const GET_PORTFOLIO_BY_TAGS = 'GET_PORTFOLIO_BY_TAGS';
export const GET_PORTFOLIO_BY_TECHNOLOGY = 'GET_PORTFOLIO_BY_TECHNOLOGY';
