#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

echo '🛠 Testing and building your project before committing...'

# Check Prettier standards
npm run check:format ||
(
  echo '⚠ Prettier Check Failed.
    Run `npm run format`, add changes, and try commit again.';
  false;
)

# Check ESLint Standards
npm run check:lint ||
(
  echo '⚠ Lint Check Failed.
    Make the required changes listed above, add changes, and try to commit again.'
  false; 
)

# Check tsconfig standards
npm run check:types ||
(
  echo '⚠ Type Check Failed.
    Make the required changes listed above, add changes, and try to commit again.'
  false;
)

# check passes
echo '🎉 Test complete...
  ⚙ Building project...'

npm run build ||
(
  echo '⚠ Build Failed.
    Check the error above for more information.'
  false;
)

# build passes
echo '🎉 All check complete!'
